Separate arch packages
mantidproject/mantidimaging pull request #1791
Opened 2023-05-12 11:19 UTC by samtygier-stfc

### Issue

Closes #1788

### Description
Make package arch specific to allow different dependancies

### Testing 

*Describe the tests that were used to verify your changes*.

### Acceptance Criteria 

*How should the reviewer test your changes*?

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

2023-05-12 17:05 UTC, samtygier-stfc commented
Getting build failures on windows

```
2023-05-12T14:17:05.0807510Z done
2023-05-12T14:17:05.6677118Z Traceback (most recent call last):
2023-05-12T14:17:05.6678077Z   File "C:\Miniconda3\envs\build-env\conda-bld\mantidimaging_1683896341611\test_tmp\run_test.py", line 2, in <module>
2023-05-12T14:17:05.6679057Z     import mantidimaging
2023-05-12T14:17:05.6683366Z ModuleNotFoundError: No module named 'mantidimaging'
2023-05-12T14:17:07.2302910Z Tests failed for mantidimaging-2.6.0a1.post4-py39_1.tar.bz2 - moving package to C:\Miniconda3\envs\build-env\conda-bld\broken
2023-05-12T14:17:07.2303961Z WARNING:conda_build.build:Tests failed for mantidimaging-2.6.0a1.post4-py39_1.tar.bz2 - moving package to C:\Miniconda3\envs\build-env\conda-bld\broken
```

This might be important
```
2023-05-12T13:35:32.5951727Z Packaging mantidimaging
2023-05-12T13:35:32.5952086Z INFO:conda_build.build:Packaging mantidimaging
2023-05-12T13:35:32.6791347Z Packaging mantidimaging-2.6.0a1.post4-py39_1
2023-05-12T13:35:32.6792242Z INFO:conda_build.build:Packaging mantidimaging-2.6.0a1.post4-py39_1
2023-05-12T13:35:32.9282931Z No files or script found for output mantidimaging
2023-05-12T13:35:32.9283634Z WARNING:conda_build.build:No files or script found for output mantidimaging
2023-05-12T13:36:40.7129205Z Unknown format
2023-05-12T13:36:40.7208665Z Unknown format
```

2023-05-15 07:59 UTC, samtygier-stfc commented
I think 3ed3e606d4d1aa4439fcf604b06aee6a45331003 may be the issue. Previously the build command was defined in the meta.yaml. This commit added a `build.sh` for linux, but not a corresponding `bld.bat` for windows.

2023-05-15 11:31 UTC, samtygier-stfc commented
Adding `bld.bat` gets it working. Package installs and runs on windows.
Just need to revert `build`/`host` change to see if that was needed.

2023-05-15 15:37 UTC, samtygier-stfc commented
![image](https://github.com/mantidproject/mantidimaging/assets/74248560/d4e58edf-66f0-4682-a9a5-0f51684ed8f6)
Success

Will rebase with the useful bits. This wont trigger a rebuild now, as its back to the original rules to build on merge to main.

2023-05-16 09:50 UTC, JackEAllen requested changes
Looks good! I can setup a nightly env on both mac and windows.
I think we should update the release notes given this is changing how we setup environments. 
Once release notes are added, happy to approve this!

2023-05-16 10:08 UTC, samtygier-stfc commented
I've put the change in the 2.5 release notes, as I intent to backport this into the stable branch

2023-05-16 10:13 UTC, JackEAllen approved these changes

2023-05-16 11:00 UTC, merged