1845 live viewer main window
mantidproject/mantidimaging pull request #1855
Opened 2023-07-07 16:42 UTC by JackEAllen

### Issue

Closes #1845 

### Description

Create basic Live Viewer Window Displaying the first .tif or .tiff image file read from a selected dataset

### Acceptance Criteria 

User can select a directory containing .tif / .tiff files from Mantid Imaging `File>Live Viewer` and a new live viewer window opens only on selecting a dataset  displaying one image from the selected directory.

### Documentation

See Next Release Notes

2023-07-07 17:04 UTC, samtygier-stfc requested changes
A few left over bits.

2023-07-07 17:04 UTC, samtygier-stfc commented on mantidimaging/gui/windows/live_viewer/view.py
> +    normalise_error_issue: str = ""
Most of these can go. I think only `imageLayout` that we want to keep.

2023-07-07 17:04 UTC, samtygier-stfc commented on mantidimaging/gui/windows/live_viewer/view.py
> +        self.main_window = main_window
Duplication

2023-07-07 17:04 UTC, samtygier-stfc commented on mantidimaging/gui/windows/live_viewer/view.py
> +        self.normalise_error_icon_pixmap = QPixmap(icon_path)
Can remove these

2023-07-07 17:04 UTC, samtygier-stfc commented on mantidimaging/gui/windows/live_viewer/view.py
> +        self._path = path
As we are not doing anything fancy with `path` it can just be a regular public attribute.

2023-07-10 07:53 UTC, JackEAllen commented
> A few left over bits.

Thanks for noticing these 👍

2023-07-10 17:34 UTC, samtygier-stfc approved these changes
Looks good

2023-07-10 18:09 UTC, merged