Avoid unneeded calculation of ROI in MIImageView
mantidproject/mantidimaging pull request #2034
Opened 2024-02-07 09:24 UTC by samtygier-stfc

### Issue

Closes #2030

### Description

Previously the ROI line plot was recalculated for every movement to a new slice, even though this does not change the plot and the plot may not be visible.

Now, this is only done on changes to the ROI and only if the ROI plot is visible.

There is also an optimisation to only call `mean()` once.

### Testing 

*Describe the tests that were used to verify your changes*.

### Acceptance Criteria 

*How should the reviewer test your changes*?

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

2024-02-12 15:49 UTC, samtygier-stfc commented
I may have reintroduced #1776 :-(

2024-02-14 14:31 UTC, JackEAllen requested changes
Looks good! just a minor suggestion to add one docstring and happy to merge! 👍

2024-02-14 14:31 UTC, JackEAllen commented on mantidimaging/gui/widgets/mi_image_view/view.py
> +    def roiClicked(self):
I would be tempted to add a docstring here to explain why we need this. If i saw this in a year's time with no context, i might question why it is needed.

2024-02-14 14:34 UTC, JackEAllen commented
Actually , just noticed a potential bug. I can't crop the image using operations>crop coordinates. after selecting a new roi shape, the roi returns back to 0,0,200,200

2024-02-14 14:37 UTC, JackEAllen commented
> Actually , just noticed a potential bug. I can't crop the image using operations>crop coordinates. after selecting a new roi shape, the roi returns back to 0,0,200,200


https://github.com/mantidproject/mantidimaging/assets/32413847/5cdeae38-f217-4bb7-b6d3-d678879639be

2024-02-14 15:09 UTC, JackEAllen approved these changes
Looks good! Happy to approve. We should probably write up an issue and associate it to this PR for reference to add a screenshot test for cropping coords within operations as I could see how this bug could have been introduced quite easily and missed in a review.

2024-02-14 15:11 UTC, samtygier-stfc commented
Yes, might be a good candidate for a system test

2024-02-14 15:34 UTC, merged