Liveview screenshot tests
mantidproject/mantidimaging pull request #2040
Opened 2024-02-13 18:05 UTC by samtygier-stfc

### Issue

Closes #2039 

### Description

*Add a description of the changes made*.

### Testing 

*Describe the tests that were used to verify your changes*.

### Acceptance Criteria 

*How should the reviewer test your changes*?

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

2024-02-14 15:13 UTC, samtygier-stfc commented on mantidimaging/eyes_tests/live_viewer_window_test.py
> +        self.imaging.live_viewer.filter_params = {"Rotate Stack": {"params": {"angle": 90}}}
If possible could we set the rotation by triggering the actual menu action. I think something like
`self.imaging.live_viewer.rotate_angles_group.actions()[1].trigger()`

2024-02-14 16:17 UTC, MikeSullivan7 commented
Could a Linux user please have a look at the `test_rotate_operation_rotates_image` screenshot on applitools? It looks and passes as expected on Windows but with the Linux screenshot it gives the error: 

> ERROR    mantidimaging.gui.windows.live_viewer.presenter:presenter.py:94 FileNotFoundError reading image: /live_dir/abc_000004.tif: [Errno 2] No such file or directory in the fake filesystem: '/proc/meminfo'

and does not display correctly: 
![image](https://github.com/mantidproject/mantidimaging/assets/30868085/26915350-8807-498e-81a3-685b1afc15eb)

compare with Windows: 
![image](https://github.com/mantidproject/mantidimaging/assets/30868085/cea4b5f8-588f-429f-8271-c7e19bf5df1a)

However I fail to see what the difference between linux and windows is here as the test is basically the same as `test_live_view_opens_with_data`

2024-02-15 16:23 UTC, samtygier-stfc commented
I've add a fix for `/dev/meminfo` and workaround for https://github.com/pytest-dev/pyfakefs/issues/949

2024-02-16 14:21 UTC, JackEAllen requested changes
Looks Good! just need to update the copyright to 2024 now that #2049 has been merged in

2024-02-16 14:21 UTC, JackEAllen commented on mantidimaging/eyes_tests/live_viewer_window_test.py
> +# Copyright (C) 2023 ISIS Rutherford Appleton Laboratory UKRI
Copyright needs to be updated to 2024

2024-02-16 14:33 UTC, JackEAllen approved these changes

2024-02-16 15:08 UTC, merged