Update documentation within the user guide for the spectrum viewer
mantidproject/mantidimaging pull request #2050
Opened 2024-02-15 18:07 UTC by JackEAllen

### Issue

Closes #2048 

### Description

Update Spectrum Viewer Documentation

### Testing 

* Proof Read to check for spelling errors
* Build Docs to check updated documentation is correctly formatted.
* Check URLs are correct.

### Acceptance Criteria 

- [ ] Documentation describes the spectrum viewer today.
- [ ] Documentation provides a good description of the spectrum viewer to someone who has never used the spectrum viewer who may have no prior experience working with tomography data. 
- [ ] No spelling or grammar errors
- [ ] All URLs work

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

2024-02-19 11:20 UTC, MikeSullivan7 requested changes
Looks great, just a few small typos :)

Would it be useful at all to include the error propagation equation which is being used in the Error Propagation mode?

2024-02-19 11:20 UTC, MikeSullivan7 commented on docs/user_guide/gui/spectrum_viewer.rst
> +To add an ROI, click the "Add" button and then click and drag the mouse over the newly created ROI within sample image to resize and position the ROI.
```suggestion
To add an ROI, click the "Add" button and then click and drag the mouse over the newly created ROI within the sample image to resize and position the ROI.
```

2024-02-19 11:20 UTC, MikeSullivan7 commented on docs/user_guide/gui/spectrum_viewer.rst
> +You can also select the step size and bin size. If the step size if the same as the bin size, a tiled average will be performed. if the step size is less than the bin size, a rolling average will be
```suggestion
You can also select the step size and bin size. If the step size if the same as the bin size, a tiled average will be performed. If the step size is less than the bin size, a rolling average will be performed. The unit of measurement is pixels.
```

2024-02-19 11:20 UTC, MikeSullivan7 commented on docs/user_guide/quick_start.rst
> +#. Select the output mode from the top drop down menu on the left which replaces the table of ROIs, either "Single Spectrum" or 2D Binned" depending on what you would like to export. 2D binned will b
```suggestion
#. Select the output mode from the top drop down menu on the left which replaces the table of ROIs, either "Single Spectrum" or 2D Binned" depending on what you would like to export. 2D binned will bin within the ROI and export the binned data as multi-spectrum data.
```

2024-02-20 10:43 UTC, JackEAllen commented
> Looks great, just a few small typos :)
> 
> Would it be useful at all to include the error propagation equation which is being used in the Error Propagation mode?

Because propagated Error is pretty standard, I think we should leave it out of our docs for the time being. If we get a user request in the future asking how we calculate it, then we can probably add it to our docs. I thinks the written description does a pretty good job of describing what error propagation is.

2024-02-20 11:54 UTC, MikeSullivan7 approved these changes

2024-02-20 12:14 UTC, merged