NaN warnings activated in the Spectrum Viewer
mantidproject/mantidimaging pull request #2186
Opened 2024-04-30 14:59 UTC by MikeSullivan7

### Issue

Closes #2185

### Description

In the `SpectrumWidget` class, the MainWindow is now passed to the `SpectrumProjectionWidget` and the `BadDataOverlay` mixin class is used in the `SpectrumProjectionWidget`.  The warning icon now appears in the Spectrum viewer when a slice which has a NaN in it is shown on the averaged image (as the NaN will propagate). The warning icon retains the same functionality as in the Main Window where it can be clicked on to open the Operations Window such that NaN removal can be performed.

### Testing 

make check

### Acceptance Criteria 

- Open MI with data which has NaNs in it (e.g. the Fe dataset)
- Open the Spectrum Viewer
- Check that if a slice in the averaged image has NaNs, then the warning icon appears
- Test this by changing the Range Control on the Spectrum plot such that a "complete" part of the plot is in the range, and the warning icon should not show.
- Move the Range Control such that an "empty" part of the plot is in the range, and the warning icon should appear. See screenshots for examples.
- Check that clicking the warning icon has the correct functionality.

![image](https://github.com/mantidproject/mantidimaging/assets/30868085/06c92995-8734-426d-a23c-b40bd6fcfdba)

![image](https://github.com/mantidproject/mantidimaging/assets/30868085/f796a10c-cff4-4443-9f90-81a208b8ac93)

### Documentation

Will add release note

2024-05-16 08:16 UTC, ashmeigh submitted a review, later dismissed

2024-05-16 08:20 UTC, samtygier-stfc commented on mantidimaging/gui/windows/spectrum_viewer/spectrum_widget.py
> +    def __init__(self, parent: MainWindowView) -> None:
Can we avoid calling this `parent` here. It has a specific meaning in Qt, and caused issues before. I think best to call it `main_window`.

2024-05-16 08:23 UTC, samtygier-stfc commented on mantidimaging/gui/windows/spectrum_viewer/spectrum_widget.py
> +    def __init__(self, parent: MainWindowView) -> None:
See https://github.com/mantidproject/mantidimaging/pull/1989

The key bit is not passing it to the Qt widget constructor, but still best to call it `main_window`

2024-05-16 08:25 UTC, samtygier-stfc requested changes
See comment

2024-06-07 09:41 UTC, samtygier-stfc approved these changes
Looks good now.

Tested with data, shows NaNs and loads correct tools.

2024-06-07 09:57 UTC, merged