Apply Shuttercount Normalisation Correction when shutterCounts Available
mantidproject/mantidimaging pull request #2214
Opened 2024-06-03 15:15 UTC by JackEAllen

### Issue

Closes #2095 

### Description

*Add a description of the changes made*.
* Load ShutterCount Files into Spectrum Viewer is initially loaded in by user.
* Apply ShutterCount correction to normalisation using only first value, but written such that more values can be used later on should requirements change.

### Testing 

*Describe the tests that were used to verify your changes*.

### Acceptance Criteria 

*How should the reviewer test your changes*?

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

2024-06-17 14:53 UTC, samtygier-stfc requested changes

2024-06-19 08:42 UTC, JackEAllen commented on mantidimaging/gui/windows/spectrum_viewer/model.py
> +    def get_transmission_error_standard_dev(self, roi: SensibleROI, normalised: bool = True) -> np.ndarray:
Thanks for spotting this. This was left set to false for testing

2024-06-19 10:40 UTC, samtygier-stfc requested changes

2024-06-19 10:40 UTC, samtygier-stfc commented on mantidimaging/gui/windows/spectrum_viewer/model.py
> +                                          normalise_with_shuttercount: bool = True) -> np.ndarray:
This one should also be false

2024-06-19 10:43 UTC, samtygier-stfc commented on mantidimaging/gui/windows/spectrum_viewer/model.py
> +            average_shuttercount = self.get_shuttercount_normalised_correction_parameter()
This is a stray line, its not needed as there  the same at 240 in the if statement

2024-06-19 12:10 UTC, samtygier-stfc approved these changes
Code looks good. I have tested with a few extra print statements to see the normalisation happening.

2024-06-19 12:28 UTC, merged