Add Type Annotations for Improved Type Safety in Windows
mantidproject/mantidimaging pull request #2251
Opened 2024-07-03 19:40 UTC by ashmeigh

### Description

Added type annotations to various functions and methods within the mantidimaging/gui/windows directory to enhance type safety and improve code maintainability. These annotations ensure clearer function signatures and better compatibility with Python type checkers like mypy.

### Testing 

Type annotations do not introduce runtime errors.
Functionality across affected modules remains intact.
All affected code paths are covered by existing unit tests.

### Acceptance Criteria 

Mannual testing 
No linting errors related to type annotations.
No type-related runtime errors occur during testing.
All affected code paths are adequately covered by existing tests.

2024-07-04 08:27 UTC, samtygier-stfc requested changes
There are a few argument types that could be added aswell.

2024-07-04 08:27 UTC, samtygier-stfc commented on mantidimaging/gui/windows/welcome_screen/presenter.py
> +    def add_link(self, link_name, url) -> None:
Argument types, probably `str`

2024-07-04 08:27 UTC, samtygier-stfc commented on mantidimaging/gui/windows/welcome_screen/view.py
> +    def set_version_label(self, contents) -> None:
Argument types

2024-07-04 08:27 UTC, samtygier-stfc commented on mantidimaging/gui/windows/welcome_screen/view.py
> +    def add_issues(self, contents) -> None:
And here

2024-07-10 12:08 UTC, MikeSullivan7 approved these changes
Looks good, all tests pass and MI runs as normal with no errors.

2024-07-10 13:16 UTC, samtygier-stfc approved these changes

2024-07-10 13:17 UTC, merged