docs: Enhance developer documentation for testing and static analysis
mantidproject/mantidimaging pull request #2316
Opened 2024-08-13 14:04 UTC by ashmeigh

### Issue

Closes #2279 

### Description

*Add a description of the changes made*.

### Testing 

This PR enhances the public-facing developer documentation for Mantid Imaging, making it more accessible to new contributors. Key updates include:

Detailed Descriptions of make Commands:
Expanded explanations for commands like make test, make test-verbose, make test-system, and more.
Instructions on modifying commands, such as adding delays to screenshot tests.

Static Analysis Tools:
Added guidance on using mypy, ruff, and yapf.

Pre-Commit Hooks:
Instructions for setting up and using pre-commit hooks.

### Acceptance Criteria 

Confirm the documentation's clarity and correctness.
Verify the functionality of the make commands as described.

### Documentation

Changes have been added to the appropriate sections, including docs/release_notes, for the upcoming release.

2024-08-13 14:10 UTC, ashmeigh commented
Other things that i think should be added are 

Running a Specific Test Module:
python -m unittest 

Using pytest for Specific Tests:
pytest -k "test"

More detail in the logging and GUI

2024-08-19 16:53 UTC, samtygier-stfc requested changes

2024-08-19 16:53 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +- :code:`yapf <https://github.com/google/yapf>`: Formats code according to PEP 8 standards, ensuring consistent style.
Can you make these links, e.g.

```
- `mypy <http://mypy-lang.org/>`_: Enforces type correctness to catch potential type errors early.
```

2024-08-19 16:53 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +    python -m unittest path.to.your_test_module
Need a double colon `::` to make a code box.

Also, lets stick to pytest commands for consistancy

`pytest path/to/test_file.py`

2024-08-19 16:53 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +  By default, screenshots are saved to a predefined directory. You can customize the output directory by setting the :code:`APPLITOOLS_IMAGE_DIR` environment variable. For example:
`::`

2024-08-19 16:53 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +- **Windows-Specific Testing**: For running screenshot tests specifically on Windows, use the following command:
`::`

2024-08-19 16:53 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +If you want to upload the screenshots to the Applitools API for comparison with baseline images stored on their servers, you need to set the :code:`APPLITOOLS_API_KEY` environment variable, which can
`::`

2024-08-19 16:53 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
Can we add:
```
See the Pytest docs for additional `command line options <https://docs.pytest.org/en/stable/reference/reference.html#command-line-flags>`.
```

2024-08-20 14:48 UTC, samtygier-stfc requested changes

2024-08-20 14:48 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +    pytest -m path/to/test_file.py
I think the `-m` is not need here.

2024-08-20 14:48 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +See the Pytest docs for additional `command line options <https://docs.pytest.org/en/stable/reference/reference.html#command-line-flags>`.
Needs the `_` at the end to make it a link.

```
See the Pytest docs for additional `command line options <https://docs.pytest.org/en/stable/reference/reference.html#command-line-flags>`_.
```

2024-08-20 14:48 UTC, samtygier-stfc commented on docs/developer_guide/testing.rst
> +
These need the `:code:` removing to make the links work

2024-09-10 08:25 UTC, samtygier-stfc approved these changes
Thanks. Links all work now.

2024-09-10 08:25 UTC, merged