Use the pixel size provided in recon preview image
mantidproject/mantidimaging pull request #630
Opened 2020-10-29 16:26 UTC by dtasev

Now uses pixel size in recon preview and reconstruct slice. Reconstruct volume already used it so nothing should be changed there.

Changing the histogram also resets the histogram range on the recon slice, so if you manually scroll up the pixel size you should see the range remaining at the edges of the data range.

Fixes #626

2020-11-02 15:13 UTC, Pasarus commented
The preview doesn't seem to use pixel size 1 micron when it opens and still shows me: 
![image](https://user-images.githubusercontent.com/24723609/97884226-bbfb5580-1d1d-11eb-9901-c026c827acd5.png)
Would it be possible to make it do the same for when it first opens the window? To get it to do that it will probably just be setting the pixel size to 1 micron before generating the images.

2020-11-02 15:14 UTC, Pasarus requested changes
Above

2020-11-03 15:29 UTC, dtasev commented
I rebased on master which has #628 and I don't think I can replicate this anymore, I did the following steps:

- Load data, set the pixel size to 1
- Go to recon window after loading
- The pixel size field was 1 and the data had been divided correctly

Can you check if this works for you?

2020-11-05 09:20 UTC, Pasarus approved these changes
It seems to work now :/ sometimes it be like that!

2020-11-05 09:20 UTC, merged