Adds source file path to IMATLogFile, shows it in metadata
mantidproject/mantidimaging pull request #733
Opened 2020-11-30 12:45 UTC by dtasev

Adds source file path to IMATLogFile, shows the file path in the metadata.

Also: 
- Adds separators in StackVisualiser context menu (main window and select ROI)

Fixes #702

2020-11-30 16:52 UTC, Pasarus requested changes
If I attempt to load a log, that has a different number of projections in it to the images loaded, it adds a log_file section to the history/metadata window, but the log is not used. Fix that and this should be ready to go!

2020-12-01 13:30 UTC, dtasev commented
Latest changes should fix that

2020-12-01 17:15 UTC, dtasev commented
Coverage should be fine now 👍 Added tests for the new branches I introduced in https://github.com/mantidproject/mantidimaging/pull/733/commits/dd46fc62b6a3f5adce4a340a67d19f6efb89b255

2020-12-02 09:36 UTC, Pasarus approved these changes

2020-12-02 09:37 UTC, merged