Adds projection angles load option
mantidproject/mantidimaging pull request #737
Opened 2020-12-01 18:22 UTC by dtasev

Adds the option to load a projection angles file from the main window.

Also:
- Adds projection angles handling in images. Projection angles from logs are still top priority.
- Adds a simple parser for 2 formats of projection angles

The supported formats are comma separated or new-line separated:
```
0,0.1,0.2,0.3...
```
and
```
0
0.1
0.2
...
```

To test:
- Load a preview stack (only 11 images)
- To test either of the two formats copy and paste this into some file that you can select as a projection angle from File > Load proj angles
	- Test with/without a new line at the end. 

```
0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0
```
and
```
0
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
1.0
```

2020-12-02 11:15 UTC, Pasarus requested changes
Just a few comments, functionally it works great and is almost ready to be merged!

2020-12-02 15:24 UTC, dtasev commented on mantidimaging/gui/windows/main/view.py
> +                                                          filter="All (*.*)")
We're not expecting any specific files, could be txt, csv, etc. I'd rather just leave it to the users to find it.

2020-12-02 15:25 UTC, dtasev commented on mantidimaging/core/utility/test/projection_angle_parser_test.py
> +# def test_angles_as_file_newline_list():
Good catch, I forgot to remove it after merging it into a single parametrized test

2020-12-03 12:45 UTC, Pasarus approved these changes

2020-12-03 13:37 UTC, merged