823: Transpose colour palette
mantidproject/mantidimaging pull request #837
Opened 2021-01-25 16:48 UTC by DolicaAkelloEgwel

### Issue

Closes #823

### Description

*Add a description of the changes made*.

### Testing 

*Describe the tests that were used to verify your changes*.

### Acceptance Criteria 

*How should the reviewer test your changes*?

### Documentation

*How have you changed the documentation to reflect your changes? All changes should be noted in the appropriate file in docs/release_notes*

2021-02-05 18:08 UTC, samtygier-stfc requested changes
Looking good so far. If it can be shifted over to the reconstructed view I think that will show its usefulness better.

Later on it might be best to move it from ReconstructWindowView to MIImageView so that it can be used more widely.

2021-02-05 18:08 UTC, samtygier-stfc commented on mantidimaging/gui/windows/recon/view.py
> +        for hist in self.hists:
At the moment this is only applying to a single image, so there no need to add 'Auto' to all the menus.

2021-02-05 18:08 UTC, samtygier-stfc commented on mantidimaging/gui/windows/recon/view.py
> +        change_colour_palette = PaletteChangerView(self, self.hists, self.image_view.projection.image)
Can you move this all to work on the reconstructed view `self.image_view.recon.image`

2021-02-09 17:15 UTC, samtygier-stfc requested changes
Looking good. Happy to merge it with the copyright date updated.

2021-02-10 11:33 UTC, DolicaAkelloEgwel commented on mantidimaging/gui/widgets/palette_changer/__init__.py
> +# Copyright (C) 2020 ISIS Rutherford Appleton Laboratory UKRI
I've just changed this but the copyright check is failing. Will this fix itself after the merge...?

2021-02-10 12:21 UTC, samtygier-stfc approved these changes

2021-02-10 12:26 UTC, merged

2021-02-10 12:26 UTC, samtygier-stfc commented
Last test issues due to jenkspy module in docker. Should fix itself once this is in master.